### ISSUE TITLE
Slug Update Event Incredibly Slow

### ISSUE THREAD

**Issue by nickpoulos** [drobee/nova-sluggable#27]
I am not 100% sure what is going on under the hood, but I just did a fresh install on a new project, and the Slug field takes a ridiculous amount of time to update.   

 I do not think it is something in my local environment, when I switch to: `benjaminhirsch/nova-slug-field` this problem disappears and updates happen near-instant.

**Comment by drobee** [comment]
@nickpoulos the `benjaminhirsch/nova-slug-field` package uses a different approach, it generates the slug on the client side by using [speakingurl](https://github.com/pid/speakingurl) while `nova-sluggable` always sends an XHR request to the backend so it has to be slower by design.
If you just want to generate a simple slug for a text field the other package is a good choice too.

You can enhance the speed of the slug generation by disabling unique slugs for your models, but since it's disabled by default I guess you have a reason to use it.
